version: '3.1'

services:
  db:
    image: 'postgres:15.2'
    container_name: backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backend
    ports:
      - "5432:5432"