CREATE TABLE product.laptop (
    id UUID NOT NULL DEFAULT uuid_generate_v1(),
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    series VARCHAR(255) NOT NULL,
    part_number VARCHAR(255) NOT NULL,
    color VARCHAR(255) NOT NULL,
    demand VARCHAR(255) NOT NULL,
    cpu_series VARCHAR(255) NOT NULL,
    cpu_brand VARCHAR(255) NOT NULL,
    cpu_model VARCHAR(255) NOT NULL,
    gpu VARCHAR(255) NOT NULL,
    ram VARCHAR(255) NOT NULL,
    screen_size VARCHAR(255) NOT NULL,
    storage VARCHAR(255) NOT NULL,
    storage_gateway VARCHAR(255) NOT NULL,
    m2_support VARCHAR(255) NOT NULL,
    output_port VARCHAR(255) NOT NULL,
    connect_port VARCHAR(255) NOT NULL,
    wireless_connect VARCHAR(255) NOT NULL,
    key_board VARCHAR(255) NOT NULL,
    os VARCHAR(255) NOT NULL,
    size VARCHAR(255) NOT NULL,
    battery VARCHAR(255) NOT NULL,
    weight DECIMAL(10, 1) NOT NULL,
    led_indicator VARCHAR(255) NOT NULL,
    accessories_included VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    quantity INT NOT NULL CHECK ( quantity >= 0 ),
    image VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
)